### ISSUE TITLE
The way to use AES.

### ISSUE THREAD

**Issue by sunoru** [sunoru/RNG.jl#10]
AES encryption is an important part of the RNGs for secure use. There are some methods to use AES:
1. Implement the encryption algorithm in pure Julia. There are also existing packages such as [AES.jl](https://github.com/faf0/AES.jl) (but this is not registered), and [Nettle.jl](http://github.com/staticfloat/Nettle.jl) (though this also provides many other functions).
2. Use the mature OpenSSL. This may also have two different ways: to wrap it by ourselves or use the existing ones (for example, [Crypto.jl](http://github.com/danielsuo/Crypto.jl), but it is not completed so doesn't guarantee the security)...

It would be better if we can directly use AES-NI on the most kinds of CPU, so I'm also wondering how will llvm do with this? Anyway, OpenSSL should have been already optimized about such things.

**Comment by sunoru** [comment]
When trying to use the AES intrinsics (as https://github.com/frasercrmck/llvm-leg/blob/master/test/CodeGen/X86/aes_intrinsics.ll), I found for now the llvmcall only accepts array-like ABI such as `[2 x i64]` (https://github.com/JuliaLang/julia/commit/a93e9a1f80df6caf8803b9ab3a47509f7b29b613), but to use the intrinsics it's necessary to pass `<2 x i64>`
```julia
julia> function aesenc(x::Tuple{UInt64, UInt64}, y::Tuple{UInt64, UInt64})
           Base.llvmcall(("""declare <2 x i64> @llvm.x86.aesni.aesenc(<2 x i64>, <2 x i64>)""","""
               %3 = call <2 x i64> @llvm.x86.aesni.aesenc(<2 x i64> %0, <2 x i64> %1)
           ret <2 x i64> %3"""), Tuple{UInt64, UInt64}, Tuple{Tuple{UInt64, UInt64}, Tuple{UInt64, UInt64}}, x, y)
       end
aesenc (generic function with 1 method)

julia> aesenc((1 % UInt64, 1 % UInt64), (1 % UInt64, 1 % UInt64))
ERROR: error compiling aesenc: Failed to parse LLVM Assembly: 
julia: llvmcall:5:58: error: '%0' defined with type '[2 x i64]'
    %3 = call <2 x i64> @llvm.x86.aesni.aesenc(<2 x i64> %0, <2 x i64> %1)
                                                         ^

 in eval(::Module, ::Any) at ./boot.jl:231
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
```

**Comment by simonbyrne** [comment]
Sorry we haven't had a chance to chat recently, I've been travelling a lot. The distinction here is between what LLVM terms vectors and arrays. From what I understand (which may well be wrong), vectors are what can be used with SIMD functions, whereas arrays are more general structs.

In 0.5 you can use `VecElement` introduced by https://github.com/JuliaLang/julia/pull/15244 inside `Tuple`s:
```
julia> function aesenc(x, y)
                  Base.llvmcall(("""declare <2 x i64> @llvm.x86.aesni.aesenc(<2 x i64>, <2 x i64>)""","""
                      %3 = call <2 x i64> @llvm.x86.aesni.aesenc(<2 x i64> %0, <2 x i64> %1)
                  ret <2 x i64> %3"""), NTuple{2,VecElement{UInt64}}, Tuple{NTuple{2,VecElement{UInt64}},NTuple{2,VecElement{UInt64}}}, x, y)
              end
aesenc (generic function with 1 method)

julia> aesenc((VecElement(1 % UInt64), VecElement(1 % UInt64)), (VecElement(1 % UInt64), VecElement(1 % UInt64)))
(VecElement{UInt64}(0x63636363427c7c5c),VecElement{UInt64}(0x63636363427c7c5c))

julia> @code_native aesenc((VecElement(1 % UInt64), VecElement(1 % UInt64)), (VecElement(1 % UInt64), VecElement(1 % UInt64)))
	.section	__TEXT,__text,regular,pure_instructions
Filename: REPL[1]
	pushq	%rbp
	movq	%rsp, %rbp
Source line: 2
	vaesenc	%xmm1, %xmm0, %xmm0
	popq	%rbp
	retq
	nopl	(%rax,%rax)
```

**Comment by sunoru** [comment]
Thanks, that's what I need.
