### ISSUE TITLE
Base.randn MethodError

### ISSUE THREAD

**Issue by fiatflux** [sunoru/RNG.jl#16]
MethodError is raised when trying to use some RNGs from this package.

Steps to reproduce (for example):
`using RNG.Random123; randn(Philox4x())`

Haven't yet investigated whether this is a package issue or upstream, but want to file an issue somewhere so I don't forget.

**Comment by sunoru** [comment]
Hi Gregor, thank you for finding this issue!

I'm so sorry that I haven't tested the `randn` functions. The error is caused by the need of `rand_ui52` in the implementation of `Base.Random.randn`. https://github.com/sunoru/RNG.jl/commit/e24994e562d9ad0d6ab0a6c5b52f4fe756bd4bd0 should fix this.
