### ISSUE TITLE
Circular shifts

### ISSUE THREAD

**Issue by simonbyrne** [sunoru/RNG.jl#6]
You had a comment about moving circular shifts to assembly. One alternative is to use llvmcall:
```julia
function llvm_rotr(x::UInt64, y::UInt64)
    Base.llvmcall("""
                %3 = lshr i64 %0, %1
                %4 = sub i64 64, %1
                %5 = shl i64 %0, %4
                %6 = or i64 %3, %5
                ret i64 %6
              """,UInt64, Tuple{UInt64,UInt64},x,y)
end
```
then using 0.4, or 0.5 with -O3 (which is how packages are precompiled), gives the appropriate `rorq` instruction.

**Comment by simonbyrne** [comment]
This seems to work as desired on 0.5 (with -O3), but not on 0.4
```julia
function rotr(x,y)
       s = sizeof(x) << 3
       r = y % s
       l = (s-r) % s
       (x >> r) | (x << l)
end
```

**Comment by sunoru** [comment]
Thanks, Simon. The former one seems very nice, I'll use this.

BTW there's a typo in the codes that it should be `%4 = sub i64 64, %1`

**Comment by simonbyrne** [comment]
Why would it be 63, not 64?

**Comment by simonbyrne** [comment]
I would suggest the latter one: the generality is well worth it, and hopefully 0.5 should be released by the time we're performance tuning.

**Comment by sunoru** [comment]
Oh I just found myself wrong.

Okay, it's reasonable to take the second function.

**Comment by sunoru** [comment]
Yesterday did you mean that I should just write
```@inline function pcg_rotr(x::UIntTypes, y::UIntTypes)
        s = sizeof(x) << 3
        (x >> (y % s)) | (x << (-y % s))
    end
```
instead of the current `@eval` form?

**Comment by simonbyrne** [comment]
Yes, exactly: `@eval` gets you nothing in this case (each combination of concrete `UInt` types will still be JIT-ed).

You could even do this for a lot of the other functions, as it seems like the constants can mostly be computed (and so will be evaluated at compile time).

**Comment by simonbyrne** [comment]
e.g. for XSH RR, you could include in the function
```julia
    s = sizeof(state) << 3
    t = trailing_zeros(s)-1 # log2(s)-1
    p1 = (s>>1 + t)>>1
    p2 = s>>1 - t
    p3 = s-t
```

**Comment by simonbyrne** [comment]
Though for 128 bits, this gives a `p1` as 35, not 29 as in your code: where did you get the constants from?

**Comment by sunoru** [comment]
I copied the constants in the PCG sources. http://www.pcg-random.org/download.html

**Comment by simonbyrne** [comment]
Ah, I see. I opened an issue here:
https://github.com/imneme/pcg-c-basic/issues/7

I guess we see what the author says.
